# Statistics and Simulation

> How likely is it that I get 2 or more heads after flipping 3 coins?

In [259]:
import pandas as pd

In [39]:
import random as r

results = []
for n in range(1000):
    coin_flips = r.choice(['Heads', 'Tails']), r.choice(['Heads', 'Tails']), r.choice(['Heads', 'Tails'])
    # print(coin_flips)
    n_heads = 0
    for flip in coin_flips:
        if flip == 'Heads':
            n_heads += 1
    results.append(n_heads)

In [37]:
two_or_more_heads = [1 if r >= 2 else 0 for r in results]
sum(two_or_more_heads) / len(two_or_more_heads)

0.498

In [68]:
import numpy as np

simulations = np.random.choice([1, 0], size=(3000)).reshape(1000, 3)
n_heads_per_simulation = simulations.sum(axis=1)
we_got_2_or_more_heads = n_heads_per_simulation >= 2
we_got_2_or_more_heads.mean()

In [70]:
simulations = np.random.choice([1, 0], size=(18)).reshape(6, 3)
simulations

array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 1],
       [1, 0, 1]])

In [72]:
n_heads_per_simulation = simulations.sum(axis=1)
n_heads_per_simulation

array([0, 1, 2, 1, 2, 2])

In [73]:
we_got_2_or_more_heads = n_heads_per_simulation >= 2
we_got_2_or_more_heads

array([False, False,  True, False,  True,  True])

In [74]:
we_got_2_or_more_heads.mean()

0.5

How to do simulation in python:

1. Figure out how to represent your data (1 = heads, 0 = tails)
1. Create a matrix of random numbers, rows represent simulations (one go-through of the experiment), columns represent trials (one event within the experiment, in our case, 1 coin flip)
1. Apply an aggregation row-wise to summarize each simulation (sum for the total number of heads)
1. Apply an aggregation to the resulting 1-d array to come up with a experimental probability (>= 2 heads, mean)

[More on random number generation][1]

[1]: https://en.wikipedia.org/wiki/Pseudorandom_number_generator

> You are at a carnival and come across a person in a booth offering you a game of "chance" (as people in booths at carnivals tend to do).
> 
> You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater than 12, you get 15 dollars. If it's less than or equal to 12, you get nothing.
> 
> Assuming the dice are fair, should you play this game? How would this change if the winning condition was a sum greater than or equal to 12?

In [134]:
n_trials = 3
n_simulations = 10_000

# (np.random.randint(1, 7, size=(n_simulations, n_trials)).sum(axis=1) > 12).mean()
dice_rolls = np.random.randint(1, 7, size=(n_simulations, n_trials))
sum_of_3_dice_rolls = dice_rolls.sum(axis=1)
did_we_win = sum_of_3_dice_rolls > 12
did_we_win.mean()

0.261

In [137]:
np.where(did_we_win, 10, -5).sum()

-10850

In [144]:
n_trials = 3
n_simulations = 10_000

# (np.random.randint(1, 7, size=(n_simulations, n_trials)).sum(axis=1) > 12).mean()
dice_rolls = np.random.randint(1, 7, size=(n_simulations, n_trials))
sum_of_3_dice_rolls = dice_rolls.sum(axis=1)
did_we_win = sum_of_3_dice_rolls >= 12
winnings = np.where(did_we_win, 10, -5).sum()
winnings

5560

> There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all?

In [215]:
np.random.randn(2, 3) 
np.random.normal(10, 3, size=(2, 3))

np.random.rand(2, 3)
np.random.uniform(size=(2, 3))

array([[0.15686377, 0.52015389, 0.65199171],
       [0.59709158, 0.2178845 , 0.38744016]])

In [220]:
n_trials = 2 # 2 weekend days
n_simulations = 10_000 # arbitrary number of sims

weekend_nap_sims = np.random.uniform(size=(n_simulations, n_trials)) <= .3
n_naps_per_weekend = weekend_nap_sims.sum(axis=1)
at_least_one_nap = n_naps_per_weekend >= 1
at_least_one_nap.mean()

0.5137

In [256]:
n_trials = 2
n_simulations = 100_000

((np.random.uniform(size=(n_simulations, n_trials)) <= .3).sum(axis=1) == 0).mean()

0.48924

In [253]:
((np.random.uniform(size=(n_simulations, n_trials)) <= .3).sum(axis=1) == 2).mean()

0.09042

> What is the probability of getting at least one 3 in 3 dice rolls?

In [266]:
# 1. Figure out how to represent your data (1 = heads, 0 = tails)
# a dice roll is a random number between 1 and 6

# 2. Create a matrix of random numbers, rows represent simulations cols represent trials
rolls = pd.DataFrame(np.random.randint(1, 7, size=(10000, 3)))

# 3. Apply an aggregation row-wise to summarize each simulation (sum for the total number of heads)
did_we_get_at_least_one_3 = rolls.apply(lambda row: 3 in row.values, axis=1)

# 4. Apply an aggregation to the resulting 1-d array to come up with a experimental probability (>= 2 heads, mean)
did_we_get_at_least_one_3.mean()

0.4194

In [264]:
row = np.array([1, 2, 4])

3 in row

False

In [276]:
# Same problem without a dataframe

# 1. Figure out how to represent your data (1 = heads, 0 = tails)
# a dice roll is a random number between 1 and 6

# 2. Create a matrix of random numbers, rows represent simulations cols represent trials
rolls = np.random.randint(1, 7, size=(10000, 3))

# 3. Apply an aggregation row-wise to summarize each simulation (sum for the total number of heads)
did_we_get_at_least_one_3 = (rolls == 3).sum(axis=1) >= 1

# 4. Apply an aggregation to the resulting 1-d array to come up with a experimental probability (>= 2 heads, mean)
did_we_get_at_least_one_3.mean()

0.4254

## Demonstrating the axis= argument

In [222]:
m = np.random.randint(1, 7, size=(3, 6))
m

array([[5, 3, 4, 5, 5, 6],
       [6, 5, 2, 5, 5, 3],
       [2, 5, 1, 2, 6, 2]])

In [223]:
m.sum()

72

In [224]:
m.sum(axis=0)

array([13, 13,  7, 12, 16, 11])

In [225]:
m.sum(axis=1)

array([28, 26, 18])